### A3

In [1]:
import numpy as np
import tensorflow as tf

In [66]:
x_np = np.array([[1, 1], [2, 2]]).astype("float32")
x_np

array([[ 1.,  1.],
       [ 2.,  2.]], dtype=float32)

In [67]:
y_np = np.array([[1, 1], [2, 2], [3, 3]]).astype("float32")
y_np

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.]], dtype=float32)

In [68]:
X = tf.Variable(x_np)

In [70]:
Y = tf.Variable(y_np)

In [73]:
def matDistance(X, Y):
    # X is T X D
    # Y is K x D
    
    assert X.get_shape()[1] == Y.get_shape()[1]
    
    Y_T = tf.transpose(Y)
    XX = tf.mul(X, X)
    YY = tf.mul(Y_T, Y_T)
    
    XX = tf.reshape(tf.reduce_sum(XX, 1), [-1, 1])
    YY = tf.reshape(tf.reduce_sum(YY, 0), [1, -1])
    XY = tf.mul(2.0, tf.matmul(X, Y_T))
    
    return XX - XY + YY

In [78]:
dist = matDistance(X, Y)

In [81]:
init = tf.initialize_all_variables()

with tf.Session() as sess:
    sess.run(init)
    v = sess.run(dist)    
    print v # will show you your variable.

[[ 0.  2.  8.]
 [ 2.  0.  2.]]
